---
mysql_database: appdb
mysql_app_user: admin
mysql_dms_user: dms_user
mysql_server_id: 1
mysql_bind_address: "0.0.0.0"
mysql_binlog_retention_hours: 24
mysql_seed_file: "{{ playbook_dir }}/../scripts/populate_db.sql"
